name: null
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - "#f6efca"
    - "#1e1c1e"
    - "#529597"
    - "#8ab9b0"
    - "#355f66"
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose: []
